# Generated by Django 4.2.7 on 2025-09-30 10:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batteryreport',
            options={'ordering': ['-date_created'], 'verbose_name': 'Отчет о батарее', 'verbose_name_plural': 'Отчеты о батарее'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['-created_at'], 'verbose_name': 'Устройство', 'verbose_name_plural': 'Устройства'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-date_created'], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterField(
            model_name='batteryreport',
            name='battery_level',
            field=models.IntegerField(verbose_name='Уровень батареи'),
        ),
        migrations.AlterField(
            model_name='batteryreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='batteryreport',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='batteryreport',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battery_reports', to='devices.device', verbose_name='Устройство'),
        ),
        migrations.AlterField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='device',
            name='external_id',
            field=models.TextField(blank=True, null=True, verbose_name='Внешний ID'),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последний раз онлайн'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='device',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Токен'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='message',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='devices.device', verbose_name='Устройство'),
        ),
        migrations.AlterField(
            model_name='message',
            name='raw_payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='Исходные данные'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(max_length=255, verbose_name='Отправитель'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(verbose_name='Текст сообщения'),
        ),
    ]
