# Generated by Django 4.2.7 on 2025-10-06 07:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_telegramuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationFilter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('package_name', models.CharField(help_text='Имя пакета приложения (например: com.android.systemui)', max_length=255, unique=True, verbose_name='Имя пакета')),
                ('description', models.CharField(blank=True, help_text='Описание для чего используется этот пакет', max_length=500, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, help_text='Включена ли фильтрация для этого пакета', verbose_name='Активен')),
                ('filter_type', models.CharField(choices=[('blacklist', 'Черный список - блокировать'), ('whitelist', 'Белый список - разрешить')], default='blacklist', help_text='Тип фильтрации', max_length=20, verbose_name='Тип фильтра')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Фильтр уведомлений',
                'verbose_name_plural': 'Фильтры уведомлений',
                'ordering': ['package_name'],
            },
        ),
        migrations.AddField(
            model_name='message',
            name='filter_reason',
            field=models.CharField(blank=True, help_text='Причина, по которой уведомление было отфильтровано', max_length=500, verbose_name='Причина фильтрации'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_filtered',
            field=models.BooleanField(default=False, help_text='Было ли уведомление отфильтровано', verbose_name='Отфильтровано'),
        ),
        migrations.AddField(
            model_name='message',
            name='package_name',
            field=models.CharField(blank=True, help_text='Имя пакета приложения, отправившего уведомление', max_length=255, verbose_name='Имя пакета'),
        ),
    ]
