# Generated by Django 4.2.7 on 2025-10-06 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_notificationfilter_message_filter_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='external_id',
        ),
    ]
