# Generated by Django 4.2.7 on 2025-10-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_remove_device_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='token',
            field=models.CharField(blank=True, help_text='Токен для авторизации в боте', max_length=32, null=True, unique=True, verbose_name='Токен авторизации'),
        ),
    ]
