# Generated by Django 4.2.7 on 2025-10-08 07:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_telegramuser_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='token',
        ),
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=32, unique=True, verbose_name='Токен')),
                ('is_used', models.BooleanField(default=False, verbose_name='Использован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Использован')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.telegramuser', verbose_name='Использован пользователем')),
            ],
            options={
                'verbose_name': 'Токен авторизации',
                'verbose_name_plural': 'Токены авторизации',
                'ordering': ['-created_at'],
            },
        ),
    ]
