# Generated by Django 4.2.7 on 2025-10-16 13:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_remove_telegramuser_token_authtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name='Текст лога')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_files', to='devices.device', verbose_name='Устройство')),
            ],
            options={
                'verbose_name': 'Лог файл',
                'verbose_name_plural': 'Лог файлы',
                'ordering': ['-date_created'],
            },
        ),
    ]
