# Generated by Django 4.2.7 on 2025-10-16 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_logfile'),
    ]

    operations = [
    ]
