# Generated by Django 4.2.7 on 2025-10-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_auto_20251016_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='logfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='logs/', verbose_name='Файл лога'),
        ),
        migrations.AlterField(
            model_name='logfile',
            name='text',
            field=models.TextField(blank=True, help_text='Превью текста для отображения в админке', verbose_name='Текст лога'),
        ),
    ]
