# Generated by Django 4.2.7 on 2025-10-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_logfile_file_alter_logfile_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='owner',
            field=models.CharField(blank=True, help_text='Имя владельца устройства', max_length=255, verbose_name='Владелец'),
        ),
    ]
