# Generated by Django 4.2.7 on 2025-10-17 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_device_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='owner',
        ),
    ]
