# Generated by Django 4.2.7 on 2025-10-25 05:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0012_remove_device_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status_level', models.CharField(choices=[('SUCCESS', 'SUCCESS - Всё хорошо'), ('ATTENTION', 'ATTENTION - Требуется внимание'), ('ERROR', 'ERROR - Критическая ошибка')], help_text='Общий статус устройства', max_length=20, verbose_name='Статус устройства')),
                ('reasons', models.JSONField(blank=True, default=list, help_text='Список текстовых причин текущего состояния', verbose_name='Причины статуса')),
                ('battery_level', models.IntegerField(help_text='Уровень заряда батареи в процентах (0-100)', verbose_name='Уровень батареи')),
                ('is_charging', models.BooleanField(default=False, help_text='Заряжается ли устройство сейчас', verbose_name='Заряжается')),
                ('network_available', models.BooleanField(default=True, help_text='Есть ли доступ к интернету', verbose_name='Доступ к интернету')),
                ('unsent_notifications', models.IntegerField(default=0, help_text='Количество неотправленных уведомлений', verbose_name='Неотправленные уведомления')),
                ('last_notification_timestamp', models.DateTimeField(blank=True, help_text='Время последнего полученного уведомления', null=True, verbose_name='Последнее уведомление')),
                ('timestamp', models.BigIntegerField(help_text='Время формирования отчёта в миллисекундах UNIX', verbose_name='Время отчёта (UNIX)')),
                ('app_version', models.CharField(blank=True, help_text='Версия мобильного приложения', max_length=50, verbose_name='Версия приложения')),
                ('android_version', models.CharField(blank=True, help_text='Версия операционной системы Android', max_length=50, verbose_name='Версия Android')),
                ('device_model', models.CharField(blank=True, help_text='Модель устройства (например, Samsung Galaxy S23)', max_length=255, verbose_name='Модель устройства')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_reports', to='devices.device', verbose_name='Устройство')),
            ],
            options={
                'verbose_name': 'Статус устройства',
                'verbose_name_plural': 'Статусы устройств',
                'ordering': ['-date_created'],
            },
        ),
    ]
